-- Script de instalación de la base de datos
-- Ejecutar este archivo primero: mysql -u root < database/schema.sql
-- O desde phpMyAdmin, seleccionar la pestaña SQL y copiar/pegar el contenido

-- Crear base de datos
CREATE DATABASE IF NOT EXISTS crud_documentos;
USE crud_documentos;

-- Tabla PRO_PROCESO
CREATE TABLE IF NOT EXISTS PRO_PROCESO (
    PRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRO_NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    PRO_PREFIJO VARCHAR(10) NOT NULL UNIQUE,
    PRO_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla TIP_TIPO_DOC
CREATE TABLE IF NOT EXISTS TIP_TIPO_DOC (
    TIP_ID INT PRIMARY KEY AUTO_INCREMENT,
    TIP_NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    TIP_PREFIJO VARCHAR(10) NOT NULL UNIQUE,
    TIP_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tabla DOC_DOCUMENTO
CREATE TABLE IF NOT EXISTS DOC_DOCUMENTO (
    DOC_ID INT PRIMARY KEY AUTO_INCREMENT,
    DOC_NOMBRE VARCHAR(255) NOT NULL,
    DOC_CODIGO VARCHAR(50) NOT NULL UNIQUE,
    DOC_CONTENIDO LONGTEXT NOT NULL,
    DOC_ID_TIPO INT NOT NULL,
    DOC_ID_PROCESO INT NOT NULL,
    DOC_FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DOC_FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (DOC_ID_TIPO) REFERENCES TIP_TIPO_DOC(TIP_ID),
    FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO(PRO_ID),
    INDEX idx_codigo (DOC_CODIGO),
    INDEX idx_nombre (DOC_NOMBRE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insertar procesos
INSERT INTO PRO_PROCESO (PRO_NOMBRE, PRO_PREFIJO) VALUES
('Ingeniería', 'ING'),
('Desarrollo', 'DEV'),
('Calidad', 'CAL'),
('Operaciones', 'OPS'),
('Administración', 'ADM');

-- Insertar tipos de documentos
INSERT INTO TIP_TIPO_DOC (TIP_NOMBRE, TIP_PREFIJO) VALUES
('Instructivo', 'INS'),
('Manual', 'MAN'),
('Procedimiento', 'PRO'),
('Especificación', 'ESP'),
('Reporte', 'REP');
